sudo: required
services:
  - docker

before_install:
  - docker build -t dollypizzle/react-ecommerce -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dollypizzle/react-ecommerce npm test -- --coverage

after_success:
  # build docker images
  - docker build -t dollypizzle/ecommerce-client ./client
  - docker build -t dollypizzle/ecommerce-nginx ./nginx
  - docker build -t dollypizzle/ecommerce-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these build images and push to docker hub
  - docker push dollypizzle/ecommerce-client
  - docker push dollypizzle/ecommerce-nginx
  - docker push dollypizzle/ecommerce-server
deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: eco-aws
  env: EcoAws-env
  bucket_name: elasticbeanstalk-eu-west-2-092749212479
  bucket_path: eco-aws
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
