version: '3'
services:
  database:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  ngnix:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://database:27017/ecommerce-aws
      - JWT_SECRET=thisismynewcourse
    depends_on:
      - database
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
